### ISSUE TITLE
TypeError: Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by michaeldzjap** [spchuang/videojs-markers#27]
This appears in the js console the moment the video ends playback for the first time using videojs 5. Restarting the video again makes these messages accumulate on a continuous basis. Full output in the console (Chrome):

Uncaught TypeError: Cannot read property 'time' of undefined in videojs-markers.min.js:3

**Comment by spchuang** [comment]
I'll take a look. Thanks for reporting :)

**Comment by spchuang** [comment]
fixed it in commit 702727

**Comment by michaeldzjap** [comment]
Thank you!

**Comment by michaeldzjap** [comment]
Hmmm... After updating to your latest commit it seems this problem still persists.

**Comment by spchuang** [comment]
Can you show me an example code so I can repro?

**Comment by bigt11** [comment]
I am getting this same error if I use
 `    markers: [
      {time: 0}
    ]`

I am getting this same error if I use below.  I personally want to start with no markers.
 `    markers: [
    ]`

No error with this
 `    markers: [
      {time: 1}
    ]`

No error with this
 `    markers: [
      {time: 0},{time: 1}
    ]`

**Comment by marianoarga** [comment]
Facing the same problem, getting that error on console every second after re-playing de video

> markers: [
>                  {time: 2, text: "Marker text"}
>               ]

**Comment by mauricioklein** [comment]
Hi all!
Is this bug fixed? 
Cause I'm facing the same problem: when the video reach the end at the first time, the errors below are throw to console:

![error](https://cloud.githubusercontent.com/assets/11538662/18949567/558c1a88-8612-11e6-9dd4-da310a3901e0.png)

I've already double checked and no mark is crossing the video duration.

I would appreciate if someone could share a fix or workaround.

Thanks! :+1:

**Comment by spchuang** [comment]
Hi guys, sorry to get back so late. I can't seem to reproduce the problem when replaying video.

**Comment by spchuang** [comment]
Can you try it with the latest commit? If the problem still exists, it'll be great if you can provide a short demo that repros the issue! Thanks

**Comment by marianoarga** [comment]
Still facing the same error on console after replaying the video with the lastest commit:
VIDEOJS: ERROR: TypeError: Cannot read property 'time' of undefined(…)  
@ video.js:6359
`f.apply?f[Array.isArray(b)?"apply":"call"](d,b):f(b)};c.logByType=i,/**`

**Comment by spchuang** [comment]
@marianoarga  can you show me the code so I can try to repro?

**Comment by mauricioklein** [comment]
Does anyone found a fix (or at least a workaround) for this problem.
I don't see a pattern on this error, happening with some cases.
Thanks!

**Comment by mauricioklein** [comment]
@spchuang I think I found the error pattern:
Here, in my project (which unfortunately I can't share any code), the error happens every time the last marker **doesn't come after the video duration**. When the last marker has it's time set to after total video duration, the error doesn't happen.

Please consider that I'm creating my markers in a crescent order of times.

So, for example:
Video duration = 60s

Last marker time = 55s -> The error happens
Last marker time = 65s -> The error doesn't happens

**Comment by spchuang** [comment]
@mauricioklein it makes sense that you can't share any real code :) But can you create a small and simple demo that reproduces the issue for me? So I can debug and fix it?

**Comment by mauricioklein** [comment]
@spchuang I'll try to do so in a JSBin, but I'm not sure if I'll be able to reproduce the error. I'll let you know.

Anyway, I'm now putting an extra marker on my setup, with time = `Number.MAX_SAFE_INTEGER`, which will be always greater than the video duration, and the error is gone.

Just to clarify: I'm intercepting the markers with the `onMarkerReached` callback.

Thanks!
